//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:31:35 AM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for AdvBkRuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdvBkRuleType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="MinDay" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AdvPur" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdvBkRuleType", propOrder = {
    "value"
})
public class AdvBkRuleType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "MinDay")
    protected String minDay;
    @XmlAttribute(name = "AdvPur")
    protected String advPur;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the minDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinDay() {
        return minDay;
    }

    /**
     * Sets the value of the minDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinDay(String value) {
        this.minDay = value;
    }

    /**
     * Gets the value of the advPur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvPur() {
        return advPur;
    }

    /**
     * Sets the value of the advPur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvPur(String value) {
        this.advPur = value;
    }

}
