//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.14 at 02:21:50 PM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DailyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DailyType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="Start" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="End" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dTTR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dTXP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dTTX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dTSX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dTMT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CurCd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NbrDec" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DailyType", propOrder = {
    "value"
})
public class DailyType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "Start")
    protected String start;
    @XmlAttribute(name = "End")
    protected String end;
    @XmlAttribute(name = "dTTR")
    protected String dttr;
    @XmlAttribute(name = "dTXP")
    protected String dtxp;
    @XmlAttribute(name = "dTTX")
    protected String dttx;
    @XmlAttribute(name = "dTSX")
    protected String dtsx;
    @XmlAttribute(name = "dTMT")
    protected String dtmt;
    @XmlAttribute(name = "CurCd")
    protected String curCd;
    @XmlAttribute(name = "NbrDec")
    protected String nbrDec;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnd(String value) {
        this.end = value;
    }

    /**
     * Gets the value of the dttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTTR() {
        return dttr;
    }

    /**
     * Sets the value of the dttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTTR(String value) {
        this.dttr = value;
    }

    /**
     * Gets the value of the dtxp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTXP() {
        return dtxp;
    }

    /**
     * Sets the value of the dtxp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTXP(String value) {
        this.dtxp = value;
    }

    /**
     * Gets the value of the dttx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTTX() {
        return dttx;
    }

    /**
     * Sets the value of the dttx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTTX(String value) {
        this.dttx = value;
    }

    /**
     * Gets the value of the dtsx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTSX() {
        return dtsx;
    }

    /**
     * Sets the value of the dtsx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTSX(String value) {
        this.dtsx = value;
    }

    /**
     * Gets the value of the dtmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTMT() {
        return dtmt;
    }

    /**
     * Sets the value of the dtmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTMT(String value) {
        this.dtmt = value;
    }

    /**
     * Gets the value of the curCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurCd() {
        return curCd;
    }

    /**
     * Sets the value of the curCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurCd(String value) {
        this.curCd = value;
    }

    /**
     * Gets the value of the nbrDec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbrDec() {
        return nbrDec;
    }

    /**
     * Sets the value of the nbrDec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbrDec(String value) {
        this.nbrDec = value;
    }

}
