//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:31:35 AM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FactItmsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FactItmsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FactItm" type="{http://ameet.org/reserv/envelope}FactItmType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FactItmsType", propOrder = {
    "factItm"
})
public class FactItmsType {

    @XmlElement(name = "FactItm", required = true)
    protected FactItmType factItm;

    /**
     * Gets the value of the factItm property.
     * 
     * @return
     *     possible object is
     *     {@link FactItmType }
     *     
     */
    public FactItmType getFactItm() {
        return factItm;
    }

    /**
     * Sets the value of the factItm property.
     * 
     * @param value
     *     allowed object is
     *     {@link FactItmType }
     *     
     */
    public void setFactItm(FactItmType value) {
        this.factItm = value;
    }

}
