//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.14 at 02:21:50 PM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GteeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GteeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PayTy" type="{}PayTyType"/>
 *         &lt;element name="GteePay" type="{}GteePayType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GteeType", propOrder = {
    "payTy",
    "gteePay"
})
public class GteeType {

    @XmlElement(name = "PayTy", required = true)
    protected PayTyType payTy;
    @XmlElement(name = "GteePay", required = true)
    protected GteePayType gteePay;

    /**
     * Gets the value of the payTy property.
     * 
     * @return
     *     possible object is
     *     {@link PayTyType }
     *     
     */
    public PayTyType getPayTy() {
        return payTy;
    }

    /**
     * Sets the value of the payTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayTyType }
     *     
     */
    public void setPayTy(PayTyType value) {
        this.payTy = value;
    }

    /**
     * Gets the value of the gteePay property.
     * 
     * @return
     *     possible object is
     *     {@link GteePayType }
     *     
     */
    public GteePayType getGteePay() {
        return gteePay;
    }

    /**
     * Sets the value of the gteePay property.
     * 
     * @param value
     *     allowed object is
     *     {@link GteePayType }
     *     
     */
    public void setGteePay(GteePayType value) {
        this.gteePay = value;
    }

}
