//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:31:35 AM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HdrType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HdrType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrigSys" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrigChan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrigApp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrigTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestChan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestApp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MsgVer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MsgMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MsgID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Env" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PayloadTy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HdrType", propOrder = {
    "origSys",
    "origChan",
    "origApp",
    "origTime",
    "destChan",
    "destApp",
    "action",
    "msgVer",
    "msgMode",
    "msgID",
    "env",
    "payloadTy"
})
public class HdrType {

    @XmlElement(name = "OrigSys", required = true)
    protected String origSys;
    @XmlElement(name = "OrigChan", required = true)
    protected String origChan;
    @XmlElement(name = "OrigApp", required = true)
    protected String origApp;
    @XmlElement(name = "OrigTime", required = true)
    protected String origTime;
    @XmlElement(name = "DestChan", required = true)
    protected String destChan;
    @XmlElement(name = "DestApp", required = true)
    protected String destApp;
    @XmlElement(name = "Action", required = true)
    protected String action;
    @XmlElement(name = "MsgVer", required = true)
    protected String msgVer;
    @XmlElement(name = "MsgMode", required = true)
    protected String msgMode;
    @XmlElement(name = "MsgID", required = true)
    protected String msgID;
    @XmlElement(name = "Env", required = true)
    protected String env;
    @XmlElement(name = "PayloadTy", required = true)
    protected String payloadTy;

    /**
     * Gets the value of the origSys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigSys() {
        return origSys;
    }

    /**
     * Sets the value of the origSys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigSys(String value) {
        this.origSys = value;
    }

    /**
     * Gets the value of the origChan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigChan() {
        return origChan;
    }

    /**
     * Sets the value of the origChan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigChan(String value) {
        this.origChan = value;
    }

    /**
     * Gets the value of the origApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigApp() {
        return origApp;
    }

    /**
     * Sets the value of the origApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigApp(String value) {
        this.origApp = value;
    }

    /**
     * Gets the value of the origTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigTime() {
        return origTime;
    }

    /**
     * Sets the value of the origTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigTime(String value) {
        this.origTime = value;
    }

    /**
     * Gets the value of the destChan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestChan() {
        return destChan;
    }

    /**
     * Sets the value of the destChan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestChan(String value) {
        this.destChan = value;
    }

    /**
     * Gets the value of the destApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestApp() {
        return destApp;
    }

    /**
     * Sets the value of the destApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestApp(String value) {
        this.destApp = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the msgVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgVer() {
        return msgVer;
    }

    /**
     * Sets the value of the msgVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgVer(String value) {
        this.msgVer = value;
    }

    /**
     * Gets the value of the msgMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgMode() {
        return msgMode;
    }

    /**
     * Sets the value of the msgMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgMode(String value) {
        this.msgMode = value;
    }

    /**
     * Gets the value of the msgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the env property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnv() {
        return env;
    }

    /**
     * Sets the value of the env property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnv(String value) {
        this.env = value;
    }

    /**
     * Gets the value of the payloadTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayloadTy() {
        return payloadTy;
    }

    /**
     * Sets the value of the payloadTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayloadTy(String value) {
        this.payloadTy = value;
    }

}
