//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:31:35 AM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HtlResModRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HtlResModRSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POS" type="{http://ameet.org/reserv/envelope}POSType"/>
 *         &lt;element name="SuccessRS" type="{http://ameet.org/reserv/envelope}SuccessRSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HtlResModRSType", propOrder = {
    "pos",
    "successRS"
})
public class HtlResModRSType {

    @XmlElement(name = "POS", required = true)
    protected POSType pos;
    @XmlElement(name = "SuccessRS", required = true)
    protected SuccessRSType successRS;

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link POSType }
     *     
     */
    public POSType getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSType }
     *     
     */
    public void setPOS(POSType value) {
        this.pos = value;
    }

    /**
     * Gets the value of the successRS property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessRSType }
     *     
     */
    public SuccessRSType getSuccessRS() {
        return successRS;
    }

    /**
     * Sets the value of the successRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessRSType }
     *     
     */
    public void setSuccessRS(SuccessRSType value) {
        this.successRS = value;
    }

}
