//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.14 at 02:21:50 PM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HtlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HtlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NatCur" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LateArrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ChnCd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BrdCd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BrdNm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HtlCd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ShHtlName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HtlType", propOrder = {
    "natCur",
    "lateArrival"
})
public class HtlType {

    @XmlElement(name = "NatCur", required = true)
    protected String natCur;
    @XmlElement(name = "LateArrival", required = true)
    protected String lateArrival;
    @XmlAttribute(name = "ChnCd")
    protected String chnCd;
    @XmlAttribute(name = "BrdCd")
    protected String brdCd;
    @XmlAttribute(name = "BrdNm")
    protected String brdNm;
    @XmlAttribute(name = "HtlCd")
    protected String htlCd;
    @XmlAttribute(name = "ShHtlName")
    protected String shHtlName;

    /**
     * Gets the value of the natCur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatCur() {
        return natCur;
    }

    /**
     * Sets the value of the natCur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatCur(String value) {
        this.natCur = value;
    }

    /**
     * Gets the value of the lateArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLateArrival() {
        return lateArrival;
    }

    /**
     * Sets the value of the lateArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLateArrival(String value) {
        this.lateArrival = value;
    }

    /**
     * Gets the value of the chnCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChnCd() {
        return chnCd;
    }

    /**
     * Sets the value of the chnCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChnCd(String value) {
        this.chnCd = value;
    }

    /**
     * Gets the value of the brdCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrdCd() {
        return brdCd;
    }

    /**
     * Sets the value of the brdCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrdCd(String value) {
        this.brdCd = value;
    }

    /**
     * Gets the value of the brdNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrdNm() {
        return brdNm;
    }

    /**
     * Sets the value of the brdNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrdNm(String value) {
        this.brdNm = value;
    }

    /**
     * Gets the value of the htlCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtlCd() {
        return htlCd;
    }

    /**
     * Sets the value of the htlCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtlCd(String value) {
        this.htlCd = value;
    }

    /**
     * Gets the value of the shHtlName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShHtlName() {
        return shHtlName;
    }

    /**
     * Sets the value of the shHtlName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShHtlName(String value) {
        this.shHtlName = value;
    }

}
