//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:55:53 AM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ameet.kafkasample.model.ihg.reservation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Envelope_QNAME = new QName("http://ameet.org/reserv/envelope", "Envelope");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ameet.kafkasample.model.ihg.reservation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnvelopeType }
     * 
     */
    public EnvelopeType createEnvelopeType() {
        return new EnvelopeType();
    }

    /**
     * Create an instance of {@link GteePayType }
     * 
     */
    public GteePayType createGteePayType() {
        return new GteePayType();
    }

    /**
     * Create an instance of {@link SuccessRSType }
     * 
     */
    public SuccessRSType createSuccessRSType() {
        return new SuccessRSType();
    }

    /**
     * Create an instance of {@link DepPolType }
     * 
     */
    public DepPolType createDepPolType() {
        return new DepPolType();
    }

    /**
     * Create an instance of {@link SrvCdsType }
     * 
     */
    public SrvCdsType createSrvCdsType() {
        return new SrvCdsType();
    }

    /**
     * Create an instance of {@link TTTType }
     * 
     */
    public TTTType createTTTType() {
        return new TTTType();
    }

    /**
     * Create an instance of {@link AddrType }
     * 
     */
    public AddrType createAddrType() {
        return new AddrType();
    }

    /**
     * Create an instance of {@link NoShwPenType }
     * 
     */
    public NoShwPenType createNoShwPenType() {
        return new NoShwPenType();
    }

    /**
     * Create an instance of {@link AdvBkRuleType }
     * 
     */
    public AdvBkRuleType createAdvBkRuleType() {
        return new AdvBkRuleType();
    }

    /**
     * Create an instance of {@link FactItmType }
     * 
     */
    public FactItmType createFactItmType() {
        return new FactItmType();
    }

    /**
     * Create an instance of {@link RtItmType }
     * 
     */
    public RtItmType createRtItmType() {
        return new RtItmType();
    }

    /**
     * Create an instance of {@link GteeType }
     * 
     */
    public GteeType createGteeType() {
        return new GteeType();
    }

    /**
     * Create an instance of {@link MbrInfoType }
     * 
     */
    public MbrInfoType createMbrInfoType() {
        return new MbrInfoType();
    }

    /**
     * Create an instance of {@link HtlResModRSType }
     * 
     */
    public HtlResModRSType createHtlResModRSType() {
        return new HtlResModRSType();
    }

    /**
     * Create an instance of {@link AddrsType }
     * 
     */
    public AddrsType createAddrsType() {
        return new AddrsType();
    }

    /**
     * Create an instance of {@link SrcType }
     * 
     */
    public SrcType createSrcType() {
        return new SrcType();
    }

    /**
     * Create an instance of {@link HtlType }
     * 
     */
    public HtlType createHtlType() {
        return new HtlType();
    }

    /**
     * Create an instance of {@link PhonesType }
     * 
     */
    public PhonesType createPhonesType() {
        return new PhonesType();
    }

    /**
     * Create an instance of {@link DailyType }
     * 
     */
    public DailyType createDailyType() {
        return new DailyType();
    }

    /**
     * Create an instance of {@link OrigBkgDataType }
     * 
     */
    public OrigBkgDataType createOrigBkgDataType() {
        return new OrigBkgDataType();
    }

    /**
     * Create an instance of {@link TaxItmsType }
     * 
     */
    public TaxItmsType createTaxItmsType() {
        return new TaxItmsType();
    }

    /**
     * Create an instance of {@link SrvCdType }
     * 
     */
    public SrvCdType createSrvCdType() {
        return new SrvCdType();
    }

    /**
     * Create an instance of {@link HdrType }
     * 
     */
    public HdrType createHdrType() {
        return new HdrType();
    }

    /**
     * Create an instance of {@link LastUpdateType }
     * 
     */
    public LastUpdateType createLastUpdateType() {
        return new LastUpdateType();
    }

    /**
     * Create an instance of {@link HtlResType }
     * 
     */
    public HtlResType createHtlResType() {
        return new HtlResType();
    }

    /**
     * Create an instance of {@link TaxItmType }
     * 
     */
    public TaxItmType createTaxItmType() {
        return new TaxItmType();
    }

    /**
     * Create an instance of {@link PayTyType }
     * 
     */
    public PayTyType createPayTyType() {
        return new PayTyType();
    }

    /**
     * Create an instance of {@link CustomersType }
     * 
     */
    public CustomersType createCustomersType() {
        return new CustomersType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link RmItmType }
     * 
     */
    public RmItmType createRmItmType() {
        return new RmItmType();
    }

    /**
     * Create an instance of {@link PayloadType }
     * 
     */
    public PayloadType createPayloadType() {
        return new PayloadType();
    }

    /**
     * Create an instance of {@link XPerDataType }
     * 
     */
    public XPerDataType createXPerDataType() {
        return new XPerDataType();
    }

    /**
     * Create an instance of {@link POSType }
     * 
     */
    public POSType createPOSType() {
        return new POSType();
    }

    /**
     * Create an instance of {@link PhoneType }
     * 
     */
    public PhoneType createPhoneType() {
        return new PhoneType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link AvgRateType }
     * 
     */
    public AvgRateType createAvgRateType() {
        return new AvgRateType();
    }

    /**
     * Create an instance of {@link StayType }
     * 
     */
    public StayType createStayType() {
        return new StayType();
    }

    /**
     * Create an instance of {@link UsrAmntType }
     * 
     */
    public UsrAmntType createUsrAmntType() {
        return new UsrAmntType();
    }

    /**
     * Create an instance of {@link GteePolType }
     * 
     */
    public GteePolType createGteePolType() {
        return new GteePolType();
    }

    /**
     * Create an instance of {@link FactItmsType }
     * 
     */
    public FactItmsType createFactItmsType() {
        return new FactItmsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvelopeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ameet.org/reserv/envelope", name = "Envelope")
    public JAXBElement<EnvelopeType> createEnvelope(EnvelopeType value) {
        return new JAXBElement<EnvelopeType>(_Envelope_QNAME, EnvelopeType.class, null, value);
    }

}
