//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.14 at 02:21:50 PM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayloadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HtlResModRS" type="{}HtlResModRSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayloadType", propOrder = {
    "htlResModRS"
})
public class PayloadType {

    @XmlElement(name = "HtlResModRS", required = true)
    protected HtlResModRSType htlResModRS;

    /**
     * Gets the value of the htlResModRS property.
     * 
     * @return
     *     possible object is
     *     {@link HtlResModRSType }
     *     
     */
    public HtlResModRSType getHtlResModRS() {
        return htlResModRS;
    }

    /**
     * Sets the value of the htlResModRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link HtlResModRSType }
     *     
     */
    public void setHtlResModRS(HtlResModRSType value) {
        this.htlResModRS = value;
    }

}
