//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.14 at 02:21:50 PM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RmItmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RmItmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShRmDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LgRmDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amount" type="{}AmountType"/>
 *         &lt;element name="UsrAmnt" type="{}UsrAmntType"/>
 *         &lt;element name="AvgRate" type="{}AvgRateType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RmCd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RmCnt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MaxGst" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RmItmType", propOrder = {
    "shRmDesc",
    "lgRmDesc",
    "amount",
    "usrAmnt",
    "avgRate"
})
public class RmItmType {

    @XmlElement(name = "ShRmDesc", required = true)
    protected String shRmDesc;
    @XmlElement(name = "LgRmDesc", required = true)
    protected String lgRmDesc;
    @XmlElement(name = "Amount", required = true)
    protected AmountType amount;
    @XmlElement(name = "UsrAmnt", required = true)
    protected UsrAmntType usrAmnt;
    @XmlElement(name = "AvgRate", required = true)
    protected AvgRateType avgRate;
    @XmlAttribute(name = "RmCd")
    protected String rmCd;
    @XmlAttribute(name = "RmCnt")
    protected String rmCnt;
    @XmlAttribute(name = "MaxGst")
    protected String maxGst;

    /**
     * Gets the value of the shRmDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShRmDesc() {
        return shRmDesc;
    }

    /**
     * Sets the value of the shRmDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShRmDesc(String value) {
        this.shRmDesc = value;
    }

    /**
     * Gets the value of the lgRmDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLgRmDesc() {
        return lgRmDesc;
    }

    /**
     * Sets the value of the lgRmDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLgRmDesc(String value) {
        this.lgRmDesc = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the usrAmnt property.
     * 
     * @return
     *     possible object is
     *     {@link UsrAmntType }
     *     
     */
    public UsrAmntType getUsrAmnt() {
        return usrAmnt;
    }

    /**
     * Sets the value of the usrAmnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsrAmntType }
     *     
     */
    public void setUsrAmnt(UsrAmntType value) {
        this.usrAmnt = value;
    }

    /**
     * Gets the value of the avgRate property.
     * 
     * @return
     *     possible object is
     *     {@link AvgRateType }
     *     
     */
    public AvgRateType getAvgRate() {
        return avgRate;
    }

    /**
     * Sets the value of the avgRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvgRateType }
     *     
     */
    public void setAvgRate(AvgRateType value) {
        this.avgRate = value;
    }

    /**
     * Gets the value of the rmCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRmCd() {
        return rmCd;
    }

    /**
     * Sets the value of the rmCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRmCd(String value) {
        this.rmCd = value;
    }

    /**
     * Gets the value of the rmCnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRmCnt() {
        return rmCnt;
    }

    /**
     * Sets the value of the rmCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRmCnt(String value) {
        this.rmCnt = value;
    }

    /**
     * Gets the value of the maxGst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxGst() {
        return maxGst;
    }

    /**
     * Sets the value of the maxGst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxGst(String value) {
        this.maxGst = value;
    }

}
