//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.14 at 02:21:50 PM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RtItmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RtItmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShRtDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LgRtDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BkgMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdvBkRule" type="{}AdvBkRuleType"/>
 *         &lt;element name="GteePol" type="{}GteePolType"/>
 *         &lt;element name="XPerData" type="{}XPerDataType"/>
 *         &lt;element name="DepPol" type="{}DepPolType"/>
 *         &lt;element name="NoShwPen" type="{}NoShwPenType"/>
 *         &lt;element name="RmItm" type="{}RmItmType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RateCd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ActCd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Comm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NoRtDisp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PcPts" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CroGte" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IdReq" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CVReq" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PCReq" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HtlCxl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Hold24" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CkIn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CkOut" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MinDay" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VAdd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EasyGrp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FreeNight" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RtItmType", propOrder = {
    "shRtDesc",
    "lgRtDesc",
    "bkgMsg",
    "advBkRule",
    "gteePol",
    "xPerData",
    "depPol",
    "noShwPen",
    "rmItm"
})
public class RtItmType {

    @XmlElement(name = "ShRtDesc", required = true)
    protected String shRtDesc;
    @XmlElement(name = "LgRtDesc", required = true)
    protected String lgRtDesc;
    @XmlElement(name = "BkgMsg", required = true)
    protected String bkgMsg;
    @XmlElement(name = "AdvBkRule", required = true)
    protected AdvBkRuleType advBkRule;
    @XmlElement(name = "GteePol", required = true)
    protected GteePolType gteePol;
    @XmlElement(name = "XPerData", required = true)
    protected XPerDataType xPerData;
    @XmlElement(name = "DepPol", required = true)
    protected DepPolType depPol;
    @XmlElement(name = "NoShwPen", required = true)
    protected NoShwPenType noShwPen;
    @XmlElement(name = "RmItm", required = true)
    protected RmItmType rmItm;
    @XmlAttribute(name = "RateCd")
    protected String rateCd;
    @XmlAttribute(name = "ActCd")
    protected String actCd;
    @XmlAttribute(name = "Comm")
    protected String comm;
    @XmlAttribute(name = "NoRtDisp")
    protected String noRtDisp;
    @XmlAttribute(name = "PcPts")
    protected String pcPts;
    @XmlAttribute(name = "CroGte")
    protected String croGte;
    @XmlAttribute(name = "IdReq")
    protected String idReq;
    @XmlAttribute(name = "CVReq")
    protected String cvReq;
    @XmlAttribute(name = "PCReq")
    protected String pcReq;
    @XmlAttribute(name = "HtlCxl")
    protected String htlCxl;
    @XmlAttribute(name = "Hold24")
    protected String hold24;
    @XmlAttribute(name = "CkIn")
    protected String ckIn;
    @XmlAttribute(name = "CkOut")
    protected String ckOut;
    @XmlAttribute(name = "MinDay")
    protected String minDay;
    @XmlAttribute(name = "VAdd")
    protected String vAdd;
    @XmlAttribute(name = "EasyGrp")
    protected String easyGrp;
    @XmlAttribute(name = "FreeNight")
    protected String freeNight;
    @XmlAttribute(name = "SeqNum")
    protected String seqNum;

    /**
     * Gets the value of the shRtDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShRtDesc() {
        return shRtDesc;
    }

    /**
     * Sets the value of the shRtDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShRtDesc(String value) {
        this.shRtDesc = value;
    }

    /**
     * Gets the value of the lgRtDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLgRtDesc() {
        return lgRtDesc;
    }

    /**
     * Sets the value of the lgRtDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLgRtDesc(String value) {
        this.lgRtDesc = value;
    }

    /**
     * Gets the value of the bkgMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBkgMsg() {
        return bkgMsg;
    }

    /**
     * Sets the value of the bkgMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBkgMsg(String value) {
        this.bkgMsg = value;
    }

    /**
     * Gets the value of the advBkRule property.
     * 
     * @return
     *     possible object is
     *     {@link AdvBkRuleType }
     *     
     */
    public AdvBkRuleType getAdvBkRule() {
        return advBkRule;
    }

    /**
     * Sets the value of the advBkRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdvBkRuleType }
     *     
     */
    public void setAdvBkRule(AdvBkRuleType value) {
        this.advBkRule = value;
    }

    /**
     * Gets the value of the gteePol property.
     * 
     * @return
     *     possible object is
     *     {@link GteePolType }
     *     
     */
    public GteePolType getGteePol() {
        return gteePol;
    }

    /**
     * Sets the value of the gteePol property.
     * 
     * @param value
     *     allowed object is
     *     {@link GteePolType }
     *     
     */
    public void setGteePol(GteePolType value) {
        this.gteePol = value;
    }

    /**
     * Gets the value of the xPerData property.
     * 
     * @return
     *     possible object is
     *     {@link XPerDataType }
     *     
     */
    public XPerDataType getXPerData() {
        return xPerData;
    }

    /**
     * Sets the value of the xPerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link XPerDataType }
     *     
     */
    public void setXPerData(XPerDataType value) {
        this.xPerData = value;
    }

    /**
     * Gets the value of the depPol property.
     * 
     * @return
     *     possible object is
     *     {@link DepPolType }
     *     
     */
    public DepPolType getDepPol() {
        return depPol;
    }

    /**
     * Sets the value of the depPol property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepPolType }
     *     
     */
    public void setDepPol(DepPolType value) {
        this.depPol = value;
    }

    /**
     * Gets the value of the noShwPen property.
     * 
     * @return
     *     possible object is
     *     {@link NoShwPenType }
     *     
     */
    public NoShwPenType getNoShwPen() {
        return noShwPen;
    }

    /**
     * Sets the value of the noShwPen property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoShwPenType }
     *     
     */
    public void setNoShwPen(NoShwPenType value) {
        this.noShwPen = value;
    }

    /**
     * Gets the value of the rmItm property.
     * 
     * @return
     *     possible object is
     *     {@link RmItmType }
     *     
     */
    public RmItmType getRmItm() {
        return rmItm;
    }

    /**
     * Sets the value of the rmItm property.
     * 
     * @param value
     *     allowed object is
     *     {@link RmItmType }
     *     
     */
    public void setRmItm(RmItmType value) {
        this.rmItm = value;
    }

    /**
     * Gets the value of the rateCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCd() {
        return rateCd;
    }

    /**
     * Sets the value of the rateCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCd(String value) {
        this.rateCd = value;
    }

    /**
     * Gets the value of the actCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActCd() {
        return actCd;
    }

    /**
     * Sets the value of the actCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActCd(String value) {
        this.actCd = value;
    }

    /**
     * Gets the value of the comm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComm() {
        return comm;
    }

    /**
     * Sets the value of the comm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComm(String value) {
        this.comm = value;
    }

    /**
     * Gets the value of the noRtDisp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoRtDisp() {
        return noRtDisp;
    }

    /**
     * Sets the value of the noRtDisp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoRtDisp(String value) {
        this.noRtDisp = value;
    }

    /**
     * Gets the value of the pcPts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcPts() {
        return pcPts;
    }

    /**
     * Sets the value of the pcPts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcPts(String value) {
        this.pcPts = value;
    }

    /**
     * Gets the value of the croGte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCroGte() {
        return croGte;
    }

    /**
     * Sets the value of the croGte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCroGte(String value) {
        this.croGte = value;
    }

    /**
     * Gets the value of the idReq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdReq() {
        return idReq;
    }

    /**
     * Sets the value of the idReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdReq(String value) {
        this.idReq = value;
    }

    /**
     * Gets the value of the cvReq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVReq() {
        return cvReq;
    }

    /**
     * Sets the value of the cvReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVReq(String value) {
        this.cvReq = value;
    }

    /**
     * Gets the value of the pcReq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCReq() {
        return pcReq;
    }

    /**
     * Sets the value of the pcReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCReq(String value) {
        this.pcReq = value;
    }

    /**
     * Gets the value of the htlCxl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtlCxl() {
        return htlCxl;
    }

    /**
     * Sets the value of the htlCxl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtlCxl(String value) {
        this.htlCxl = value;
    }

    /**
     * Gets the value of the hold24 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHold24() {
        return hold24;
    }

    /**
     * Sets the value of the hold24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHold24(String value) {
        this.hold24 = value;
    }

    /**
     * Gets the value of the ckIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCkIn() {
        return ckIn;
    }

    /**
     * Sets the value of the ckIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCkIn(String value) {
        this.ckIn = value;
    }

    /**
     * Gets the value of the ckOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCkOut() {
        return ckOut;
    }

    /**
     * Sets the value of the ckOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCkOut(String value) {
        this.ckOut = value;
    }

    /**
     * Gets the value of the minDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinDay() {
        return minDay;
    }

    /**
     * Sets the value of the minDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinDay(String value) {
        this.minDay = value;
    }

    /**
     * Gets the value of the vAdd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVAdd() {
        return vAdd;
    }

    /**
     * Sets the value of the vAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVAdd(String value) {
        this.vAdd = value;
    }

    /**
     * Gets the value of the easyGrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEasyGrp() {
        return easyGrp;
    }

    /**
     * Sets the value of the easyGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEasyGrp(String value) {
        this.easyGrp = value;
    }

    /**
     * Gets the value of the freeNight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeNight() {
        return freeNight;
    }

    /**
     * Sets the value of the freeNight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeNight(String value) {
        this.freeNight = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqNum(String value) {
        this.seqNum = value;
    }

}
