//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.14 at 02:21:50 PM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for SrvCdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SrvCdType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="SrvHtl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SrvVal" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SrvTxt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SrvCdType", propOrder = {
    "value"
})
public class SrvCdType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "SrvHtl")
    protected String srvHtl;
    @XmlAttribute(name = "SrvVal")
    protected String srvVal;
    @XmlAttribute(name = "SrvTxt")
    protected String srvTxt;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the srvHtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrvHtl() {
        return srvHtl;
    }

    /**
     * Sets the value of the srvHtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrvHtl(String value) {
        this.srvHtl = value;
    }

    /**
     * Gets the value of the srvVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrvVal() {
        return srvVal;
    }

    /**
     * Sets the value of the srvVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrvVal(String value) {
        this.srvVal = value;
    }

    /**
     * Gets the value of the srvTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrvTxt() {
        return srvTxt;
    }

    /**
     * Sets the value of the srvTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrvTxt(String value) {
        this.srvTxt = value;
    }

}
