//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.14 at 02:21:50 PM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxItmsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxItmsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxItm" type="{}TaxItmType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxItmsType", propOrder = {
    "taxItm"
})
public class TaxItmsType {

    @XmlElement(name = "TaxItm", required = true)
    protected TaxItmType taxItm;

    /**
     * Gets the value of the taxItm property.
     * 
     * @return
     *     possible object is
     *     {@link TaxItmType }
     *     
     */
    public TaxItmType getTaxItm() {
        return taxItm;
    }

    /**
     * Sets the value of the taxItm property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxItmType }
     *     
     */
    public void setTaxItm(TaxItmType value) {
        this.taxItm = value;
    }

}
