//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:31:35 AM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxItmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxItmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Start" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="End" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InclTy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BasisTy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Pct" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxItmType", propOrder = {
    "taxDesc"
})
public class TaxItmType {

    @XmlElement(name = "TaxDesc", required = true)
    protected String taxDesc;
    @XmlAttribute(name = "Start")
    protected String start;
    @XmlAttribute(name = "End")
    protected String end;
    @XmlAttribute(name = "InclTy")
    protected String inclTy;
    @XmlAttribute(name = "BasisTy")
    protected String basisTy;
    @XmlAttribute(name = "Pct")
    protected String pct;

    /**
     * Gets the value of the taxDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxDesc() {
        return taxDesc;
    }

    /**
     * Sets the value of the taxDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxDesc(String value) {
        this.taxDesc = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnd(String value) {
        this.end = value;
    }

    /**
     * Gets the value of the inclTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInclTy() {
        return inclTy;
    }

    /**
     * Sets the value of the inclTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInclTy(String value) {
        this.inclTy = value;
    }

    /**
     * Gets the value of the basisTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasisTy() {
        return basisTy;
    }

    /**
     * Sets the value of the basisTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasisTy(String value) {
        this.basisTy = value;
    }

    /**
     * Gets the value of the pct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPct() {
        return pct;
    }

    /**
     * Sets the value of the pct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPct(String value) {
        this.pct = value;
    }

}
