//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.18 at 10:55:53 AM EDT 
//


package org.ameet.kafkasample.model.ihg.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TTTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTTType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="TTR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TXP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TTX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TSX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TMT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CurCd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NbrDec" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTTType", propOrder = {
    "value"
})
public class TTTType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "TTR")
    protected String ttr;
    @XmlAttribute(name = "TXP")
    protected String txp;
    @XmlAttribute(name = "TTX")
    protected String ttx;
    @XmlAttribute(name = "TSX")
    protected String tsx;
    @XmlAttribute(name = "TMT")
    protected String tmt;
    @XmlAttribute(name = "CurCd")
    protected String curCd;
    @XmlAttribute(name = "NbrDec")
    protected String nbrDec;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the ttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTTR() {
        return ttr;
    }

    /**
     * Sets the value of the ttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTTR(String value) {
        this.ttr = value;
    }

    /**
     * Gets the value of the txp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTXP() {
        return txp;
    }

    /**
     * Sets the value of the txp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTXP(String value) {
        this.txp = value;
    }

    /**
     * Gets the value of the ttx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTTX() {
        return ttx;
    }

    /**
     * Sets the value of the ttx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTTX(String value) {
        this.ttx = value;
    }

    /**
     * Gets the value of the tsx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTSX() {
        return tsx;
    }

    /**
     * Sets the value of the tsx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTSX(String value) {
        this.tsx = value;
    }

    /**
     * Gets the value of the tmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTMT() {
        return tmt;
    }

    /**
     * Sets the value of the tmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTMT(String value) {
        this.tmt = value;
    }

    /**
     * Gets the value of the curCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurCd() {
        return curCd;
    }

    /**
     * Sets the value of the curCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurCd(String value) {
        this.curCd = value;
    }

    /**
     * Gets the value of the nbrDec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbrDec() {
        return nbrDec;
    }

    /**
     * Sets the value of the nbrDec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbrDec(String value) {
        this.nbrDec = value;
    }

}
